//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoshopDBProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Orders
    {
        public int Employee_ID { get; set; }
        public int Orders_ID { get; set; }
        public int Employee_Orders_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
