//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoshopDBProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Manufacturer
    {
        public int Product_ID { get; set; }
        public Nullable<int> Manufacturer_ID { get; set; }
        public int Product_Manufacturer_ID { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Product Product { get; set; }
    }
}
